[package]
name = "pillars_ggez"
version = "0.1.0"
edition = "2018"

[dependencies]
ggez = "*"
rand = "*"
maplit = "*"
num-derive = "*"
num-traits = "*"
glam = { version = "*", features = ["mint"] }
serde = { version = "*", features = ["derive"] }
ron = "*"